version = "1.0.0"
owner = "francois.kubler@scalingo.com"
team = "IST"
description = "Official Scalingo OpenSearch Dashboards buildpack"
languages = ["shell"]
destination_server = []
flags = ["buildpack"]
dependencies = []
